wl = 1550e-9;
switchtolayout;
select('FDE');
set('wavelength',wl);

kappa2_target = 0.5; # power coupling ratio

run;
findmodes;

n_eff1 = getdata("FDE::data::mode1", "neff");
n_eff2 = getdata("FDE::data::mode2", "neff");

dn = n_eff1 - n_eff2;

C = pi*dn/wl;

L = asin(sqrt(kappa2_target))/C;
#L =(pi/(4*C))*1e6; # length (in um) required to 50/50 power coupling

E_1 = getresult("FDE::data::mode1", "E");
E_2 = getresult("FDE::data::mode2", "E");

matlabsave('Supermodes');