### return to default 
coupler_layout;
clear;

wavelength = 1550e-9;

select('FDE');
set('wavelength',wavelength);

## assume 5 nm standard deviation for width and gap values
## assume Gaussian distribution for fab errors
N = 100 ; # number of sim
sigma = 5e-9; 
gap = 150e-9;
wg_width = 450e-9;

wg_1 = wg_width + randnmatrix(N)*sigma;
wg_2 = wg_width + randnmatrix(N)*sigma;
gap_vals = gap + randnmatrix(N)*sigma; 

C= matrix(N);
n_eff1= matrix(N);
n_eff2= matrix(N);

for(i=1:N){
    
    switchtolayout;
    wg_width1 = wg_1(i);
    wg_width2 = wg_2(i);
    gap = gap_vals(i);

    select('through wg');
    setnamed('through wg::straight wg','y span', wg_width1);
    #setnamed('through wg::outgoing bend','base width', wg_width1);
    #setnamed('through wg::incoming bend','base width', wg_width1);
    set('y',(wg_width1 + gap)/2);
    
    select('coupled wg');
    setnamed('coupled wg::straight wg','y span', wg_width2);
    #setnamed('coupled wg::outgoing bend','base width', wg_width1);
    #setnamed('coupled wg::incoming bend','base width', wg_width1);
    set('y',-(wg_width2+ gap)/2);
        
    run;
    findmodes;

    n_eff1(i) = getdata("FDE::data::mode1", "neff");
    n_eff2(i) = getdata("FDE::data::mode2", "neff");

    dn = n_eff1(i) - n_eff2(i);

    C(i) = pi*dn/wavelength; # coupling coefficient
    }

matlabsave('monte_carlo_sweep');



