switchtolayout;
selectall;
delete;

## GEOM params
bg_index = 1.44;

wg_length = 6.4e-6;

wg_width = 0.45e-6;
wg_height = 220e-9;

gap = 1.5e-7;

bend_x = 4e-6;
bend_y = 1.5e-6;

## SIM PARAMS
size_fme=1.5e-6;
dy = 25e-9;
dz = 25e-9;
num_mesh_y =  size_fme / dy;
num_mesh_z =  size_fme / dz;

in_wg_length = 1e-6;

offset = 1e-7;
x_span = in_wg_length + 2*bend_x+wg_length;
x_min = -(bend_x+(in_wg_length+wg_length)/2);
x_max = x_span+x_min;

## GEOMETRY

#INPUT WAVEGUIDE
addstructuregroup;
set("name","through wg");
set('x',0);
set('y',0);
set('z',0);

addrect;
set('name','straight wg');
set('x',0);
set('x span',wg_length);
set('y',0);
set('y span',wg_width);
set('z',0);
set('z span',wg_height);
set('material','Si (Silicon) - Palik');
addtogroup("through wg");

addrect;
set('name','input wg');
set('x',x_min);
set('x span',in_wg_length);
set('y',bend_y);
set('y span',wg_width);
set('z',0);
set('z span',wg_height);
set('material','Si (Silicon) - Palik');
addtogroup("through wg");

copy;
set('name','output wg');
set('x',-x_min);
set('x span',in_wg_length);
addtogroup("through wg");

addwaveguide;
set('name', 'outgoing bend');
set("base width",wg_width);
set("base height",wg_height);
set("base angle",90);
poles = [-bend_x/2,0;
          0,0;
          0,bend_y;
          bend_x/2,bend_y];
set("poles",poles);
set('x',(wg_length+bend_x)/2);
set('z',0);
set('material','Si (Silicon) - Palik');
addtogroup("through wg");

addwaveguide;
set('name', 'incoming bend');
set("base width",wg_width);
set("base height",wg_height);
set("base angle",90);
poles = [bend_x/2,0;
          0,0;
          0,bend_y;
          -bend_x/2,bend_y];
set("poles",poles);
set('x',-(wg_length+bend_x)/2);
set('z',0);
set('material','Si (Silicon) - Palik');
addtogroup("through wg");
select('through wg');
set('y',(gap+wg_width)/2);


### coupling Waveguide
copy;
set('name', 'coupled wg');
set('y',-(gap+wg_width)/2);
set('first axis','x');
set('rotation 1',180);

### account for shift introduced by structural group 
shift_up = getnamed('through wg','y');
shift_down = getnamed('coupled wg','y');

addfdtd;
set('mesh accuracy',3);
set('index',bg_index);
set('x min',x_min);
set('x max',x_max);
set('y',0);
set('z',0);
set('y span',2*bend_y+2*wg_width+gap+1e-6);
set('z span', size_fme);

### Add source
addmode;
set('mode selection','fundamental TE');
set('name','input field');
set('x', -bend_x-wg_length/2);
set('y', bend_y+shift_up);
set('y span', wg_width*3);
set('z',0);
set('z span',size_fme);
set('set wavelength',1);
set('wavelength start',1550e-9);
set('wavelength stop',1550e-9);

### Add field monitors
addpower;
set('monitor type','2D X-normal');
set('name','through field');
set('x', bend_x+wg_length/2);
set('y', bend_y+shift_up);
set('y span', wg_width*3);
set('z',0);
set('z span',size_fme);

addpower;
set('monitor type','2D X-normal');
set('name','coupled field');
set('x', bend_x+wg_length/2);
set('y', -bend_y+shift_down);
set('y span', wg_width*3);
set('z',0);
set('z span',size_fme);

addpower;
set('monitor type','2D X-normal');
set('name','Coupling Area');
set('x', 0);
set('y', 0);
set('y span', size_fme);
set('z',0);
set('z span',size_fme);

addpower;
set('monitor type','2D Z-normal');
set('name','XY Area');
set('x', 0);
set('x span', x_span);
set('y', 0);
set('y span', 2*bend_y+2*wg_width+gap+1e-6);
set('z',0);
