switchtolayout;
selectall;
delete;

## SIM params
bg_index = 1.44;

wg_length = 15e-6;
offset  = 1e-6; # PML to Source, to Monitor, to WG offset
wg_width = 0.45e-6;
wg_height = 220e-9;

gap = 1.5e-7;

## GEOMETRY

#INPUT WAVEGUIDE
addrect;
set('name','through wg');
set('x',0);
set('x span',wg_length);
set('y',(wg_width+gap)/2);
set('y span',wg_width);
set('z',0);
set('z span',wg_height);
set('material','Si (Silicon) - Palik');

copy(0,-(wg_width+gap),0);
set('name','coupling wg');

### Add FDTD
addfdtd;
set('mesh accuracy',3);
set('index',bg_index);
set('x',0);
set('x span',wg_length-2*offset);
set('y',0);
set('z',0);
set('y span',2*wg_width+gap+2*offset);
set('z span', wg_height+2*offset);

### Add source
addmode;
set('mode selection','fundamental TE');
set('name','input field');
set('x', -wg_length/2 + 2*offset);
set('y', (wg_width+gap)/2);
set('y span', wg_width);
set('z',0);
set('z span',wg_width);
set('set wavelength',1);
set('wavelength start',1550e-9);
set('wavelength stop',1550e-9);

### Add field monitors
for (i=2:2:10){ 
addpower;
set('monitor type','2D X-normal');
set('name','coupled field_'+num2str(i));
set('x',  -wg_length/2 + 2*offset+i*1e-6);
set('y', -(wg_width+gap)/2);
set('y span', wg_width);
set('z',0);
set('z span',wg_height);
copy(0,wg_width+gap);
set('name','through field_'+num2str(i));
}

addpower;
set('monitor type','2D Z-normal');
set('name','XY Area');
set('x', 0);
set('x span', wg_length);
set('y', 0);
set('y span', 2*wg_width+gap+3*offset);
set('z',0);


### Run and get data
#T_coupled =  matrix(5);
#T_through = matrix(5);
 
#run;

#for (i=1:5){ 

#t = getresult('coupled field_'+num2str(2*i),'T');
#T_coupled(i) = t.T;


#t = getresult('through field_'+num2str(2*i),'T');
#T_through(i) = t.T;
#}

#E_xy = getresult('XY Area','E');

#matlabsave('straight_WG_data');