switchtolayout;
selectall;
delete;

## GEOM params
bg_index = 1.44;

wg_length = 2e-6;

wg_width = 0.45e-6;
wg_height = 220e-9;

gap = 1.5e-7;

bend_x = 3e-6;
bend_y = 1.5e-6;

## SIM PARAMS
size_fme=1.5e-6;
dy = 25e-9;
dz = 25e-9;
num_mesh_y =  size_fme / dy;
num_mesh_z =  size_fme / dz;

### ADD FDE ###
addfde;
set('solver type','2D X Normal');
#set('y min bc','PML');
#set('y max bc','PML');
#set('z min bc','PML');
#set('z max bc','PML');

set('x',0);
set('y',0); 
set('y span',size_fme);
set('z',0);
set('z span',size_fme);

set('mesh cells y',num_mesh_y);
set('mesh cells z',num_mesh_z);
set('index',bg_index);

set('number of trial modes',5);
## GEOMETRY

#INPUT WAVEGUIDE
addstructuregroup;
set("name","through wg");
set('x',0);
set('y',0);
set('z',0);

addrect;
set('name','straight wg');
set('x',0);
set('x span',wg_length);
set('y',0);
set('y span',wg_width);
set('z',0);
set('z span',wg_height);
set('material','Si (Silicon) - Palik');
addtogroup("through wg");

addwaveguide;
set('name', 'outgoing bend');
set("base width",wg_width);
set("base height",wg_height);
set("base angle",90);
poles = [-bend_x/2,0;
          0,0;
          0,bend_y;
          bend_x/2,bend_y];
set("poles",poles);
set('x',(wg_length+bend_x)/2);
set('z',0);
set('material','Si (Silicon) - Palik');
addtogroup("through wg");

addwaveguide;
set('name', 'incoming bend');
set("base width",wg_width);
set("base height",wg_height);
set("base angle",90);
poles = [bend_x/2,0;
          0,0;
          0,bend_y;
          -bend_x/2,bend_y];
set("poles",poles);
set('x',-(wg_length+bend_x)/2);
set('z',0);
set('material','Si (Silicon) - Palik');
addtogroup("through wg");
select('through wg');
set('y',(gap+wg_width)/2);

### coupling Waveguide
copy;
set('name', 'coupled wg');
set('y',-(gap+wg_width)/2);
set('first axis','x');
set('rotation 1',180);

### MESH region
addmesh;
set('x',0);
set('y',0);
set('z',0);
set('x span',0);
set('z span',wg_height+1e-7);
set('y span',2*wg_width+gap+2e-7);
set('override x mesh',0);
set('dy',1e-8);
set('dz',1e-8);

