#N_wavelength = 21;
#N_index_1 = 3;
#N_index_2 = 3;
#wl_start = 1.5e-6; # start wavelength
#wl_stop = 1.6e-6; #stop wavelength
index_1 = 1:N_index_1;
index_2 = 1:N_index_2;

s = matrix(N_index_1, N_index_2, N_wavelength);

wavelength_vec = linspace(wl_start,wl_stop,N_wavelength);

for(i=1:length(wavelength_vec)){
switchtolayout;

setnamed('EME','wavelength',wavelength_vec(i));

run;    
emepropagate;

swp_s_matrix = getresult('EME','user s matrix');
s(:,:,i) = swp_s_matrix;

    }
    
s_matrix = matrixdataset("s_matrix");

# Add the dataset coordinates
s_matrix.addparameter("index_1", index_1);
s_matrix.addparameter("index_2", index_2);
s_matrix.addparameter("wavelength", wavelength_vec);

# Add the completed 3D S-matrix
s_matrix.addattribute("user s matrix", s);
